### ISSUE TITLE
How to Use the video annotation instead of images in tensorflow API 

### ISSUE THREAD

**Issue by aalzooke** [ykotseruba/JAAD_dataset#1]
I have trined my model using label images annotation but i have not done in videos. Is it the same way or do i need to do anything extra in tensorflow API

**Comment by aras62** [comment]
Hi Assam, 
Thank you for your interest in our dataset. Unfortunately, we cannot help you with machine learning libraries such as Tensorflow. I recommend directing your question to corresponding forums.
