### ISSUE TITLE
Normalization in pose data?

### ISSUE THREAD

**Issue by xingchenzhang** [ykotseruba/JAAD_dataset#15]
Hi,

Many thanks for your very useful work!

Can I ask have you performed normalization for the pose data? I have observed some pose data and found the range is between 0 and 1. So I am wondering this.

Thanks a lot again!

Bests,
Xingchen

**Comment by ykotseruba** [comment]
The input bounding boxes are padded so that the pedestrian is in the center and to preserve the aspect ratio. The padded bounding box is resized to `[224,224]`, then joint coordinates are divided by `224` to be in the range `[0,1]`.

**Comment by xingchenzhang** [comment]
Thanks a lot!!
