### ISSUE TITLE
Using the interface to extract frames

### ISSUE THREAD

**Issue by gv237-07** [ykotseruba/JAAD_dataset#16]
Hi. Thank you for your work. I'm trying to use the interface to extract the frames from the videos, which I placed in JAAD\JAAD_clips. I'm giving the root folder (\JAAD) as the data path, but the images are not being extracted to the images folder. The images folder and sub-folders are all created normally but the frames are saved in the root folder. And only the frames for video 1 are saved, while the rest aren't.
Could this be a Windows issue?

**Comment by Christoph9402** [comment]
Hello, am facing the same problem. Were you able to solve it? Should I modify the "extract_and_save_images" function within jaad_data.py?

**Comment by ykotseruba** [comment]
Hi @Christoph9402,
Are you getting any errors? What is your directory structure? What are you providing as the `jaad_path`?

I just tested the code for extraction provided in the README and it worked for me.
This is my directory structure:
```
JAAD
            JAAD_clips
            annotations
            ...
```
`jaad_path` is the absolute path to the top `JAAD` directory (e.g. /home/user/JAAD).

If you are still having trouble, you can also try using the bash script. It does the same thing.

**Comment by gv237-07** [comment]
I used the bash script on Google Colab and it worked @Christoph9402

**Comment by Christoph9402** [comment]
Thanks for the replies, I found a way to make it work :)

**Comment by ykotseruba** [comment]
Hi Christoph, I'm glad to hear that you made it work! Could you please share your solution?

**Comment by johnny12150** [comment]
It seems the line 202 is wrong.
https://github.com/ykotseruba/JAAD/blob/cbae4329df2e3b3cf653eade493c5f647c126d10/jaad_data.py#L202
It should be `img_path = join(save_images_path, "{:05d}.png".format(frame_num))`.

**Edit**
This probably only happens on Windows.
> https://stackoverflow.com/questions/55710321/why-os-path-join-can-not-deal-with-string-format

**Comment by ykotseruba** [comment]
Thank you @johnny12150, this does seem to be an issue. I pushed the changes.
