### ISSUE TITLE
av_interleaved_write_frame(): Input/output error

### ISSUE THREAD

**Issue by aoteman233** [ykotseruba/JAAD_dataset#18]
The following error occurs when using the script to generate the image
00000.png of each folder will report an error
![屏幕截图 2022-02-25 124414](https://user-images.githubusercontent.com/73416150/155655364-ec38fc6e-6534-4a12-8eca-ad9538a6a06e.png)

**Comment by aoteman233** [comment]
Thank you for your efforts, this is my question, very much hope to get an answer, thank you

**Comment by ykotseruba** [comment]
The error happens when either the directory for storing the images is not created (which the script does before running ffmpeg) or because the video file is corrupt. If you haven't modified the script, I suggest downloading the videos again.
