### ISSUE TITLE
Is it possible to add pedestrian_unique_id on retinanet method results?

### ISSUE THREAD

**Issue by knakjbdhjahh** [ykotseruba/JAAD_dataset#20]
Thank you so much for providing such a wonderful dataset. 
I have a question. Is it possible to add pedestrian_unique_id on retinanet method as in the CSV results? Because, it just generates frames_id, bounding box, and pedestrian class without generating each pedestrian's unique ID.
If possible, may you teach or share here how to do it? Thank you, I would like to appreciate any help you can provide.

**Comment by ykotseruba** [comment]
Unfortunately, we cannot accommodate individual requests for adding features to the code. 
You may want to look at the ```get_detection_data()``` function, which is where ```ped_samples``` dictionary is populated and add a pedestrian id field to it. ```ped_samples``` is used to generate csv files, so simply add an extra item to each line in the file (see ```_generate_csv_data_retinanet():881```).
