### ISSUE TITLE
pedestrian trajectory files required for model(.pkl)

### ISSUE THREAD

**Issue by adibisoyi** [ykotseruba/JAAD_dataset#21]
Hi @ykotseruba , For my model I need to extract pedestrian trajectory files as .pkl files (eg. 00131_0_109_608b.pkl). Can you help on how to generate the pickle files from the images extracted from the videos.

**Comment by ykotseruba** [comment]
Hi @adibisoyi, please see the `_get_trajectories` function (lines 1040-1117 in `jaad_data.py'). This function outputs a dictionary with lists of images, coordinates, ids, etc. corresponding to the individual trajectories. For example, `bbox_seq[i]' will contain bounding boxes and `image_seq[i]' will contain images for the pedestrian with id stored in `pids_seq[i]'.
