### ISSUE TITLE
Purpose of new python files

### ISSUE THREAD

**Issue by Kalinga** [ykotseruba/JAAD_dataset#5]
Hallo, recently two new python files have been added, and i could not find any readme about it.
jaad_data.py and jaad_eval.py why and how to use them.

Is there a script available that converts the .vvb and .mat information to a JSON, because i find once the information related to bounding boxes are stored in JSON, it is easier to work with in python.

Thnaks,
Kalinga

**Comment by aras62** [comment]
Hi There,

Thanks for following up on our dataset. so those files are actually experimental and will be removed soon. We are currently working on a new set of annotations and an interface. It should be posted sometime today or tomorrow. All the new annotations are in XML and can be used with JAAD clips. This will remove the dependencies on .vbb and .seq files.

**Comment by Kalinga** [comment]
Ohh, that's sounds good. 
I believe using your new XML based annotaions, we would have enough information for  predicting the Pedestrain Intention.
