### ISSUE TITLE
Not able to use .mat file

### ISSUE THREAD

**Issue by Kalinga** [ykotseruba/JAAD_dataset#6]
Tries with matlabR2013a and R2016a versions of matlab. I am getting below errors.
Which version of matlab was used for this?

 load('video_0001.mat')
Error using load
Unable to read MAT-file C:\Users\kara9147\Documents\MATLAB\video_0001.mat: not
a binary MAT-file.
Try LOAD -ASCII to read as text.

Thanks,
Kalinga

**Comment by ykotseruba** [comment]
Hi, 
I cannot replicate your issue since I have a different version of Matlab and Ubuntu operating system. I've loaded the mat files without issues on Matlab 2015b and 2018b. 
We are going to upload the XML annotations soon, those should be easier to manage.

**Comment by Kalinga** [comment]
Ok. Thank you! Great work!
