### ISSUE TITLE
Clarity on action and reaction

### ISSUE THREAD

**Issue by Kalinga** [ykotseruba/JAAD_dataset#7]
For the video_0001
From annotaion i see for frame 363
hand_gesture

and for frame 364
reaction
action
hand_gesture

I am not able to locate what is this "reaction action" in the readme. Could you please elaborate on this. How these lables would be interesting, while predicting the Intention. I would like to use LSTM on the sequence of activities, but not sure about the activites such as "reaction action".

from jaad_data import JAAD
imdb = JAAD(data_path = jaad_path)
anno = imdb._get_annotations("video_0001")
for k,v in anno["ped_annotations"]["0_1_3b"]["behavior"].items():
    print (k)

Outputs:
cross
reaction
look
nod
action
hand_gesture

I was expecting "walking" in this output. What are the possible values apart from above output.

**Comment by aras62** [comment]
Hi There,

So 'reaction', as the name suggests, refers to the reaction of the people with respect to the driver's actions, e.g. clearing path, etc. A good place to look for these tags is in "_map_text_to_scalar" function. Basically, actions are very basic movements of the pedestrian, i.e. 'standing' and 'walking'. Reactions are rarer and only are available if there is an interaction taking place. In your case, if you want to do intention, a good starting point would be 'crossing' labels which indicate whether the person will cross '1, or not '0' or even is irrelevant '-1'. When you select 'all' samples to be generated (including the ones without behavioral data), all those pedestrians will be irrelevant. We will try to update the readme sometime soon and include more details.

**Comment by Kalinga** [comment]
Hallo, thanks for your quick reply.
One thing not clear, in the first video i could see the lady crossing the road, but from annotation i am not getting that information. sample output for last frames
560 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
561 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
562 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
563 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
564 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
565 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
566 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
567 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing
568 : clear_path-walking-nod?-not_looking-hand_gesture?-not_crossing

What does clear_path indicates in this context? I was thinking clear_path indicates pedestrain crossing and clearing the path for Vehicle. Could you please throw some light into it?

**Comment by aras62** [comment]
So to answer your question,
Our convention for crossing tags is that someone crosses from one side of the road to the other. That particular video that you mentioned, there is no crossing taking place. The lady in the video is doing something in her car and we are simply waiting for her to finish so we can park next to her car.
 
So what clear path entails? It refers to situations where the pedestrian clears the way for the vehicle to go first. Your point is correct that when someone crosses is also a form of clearing path. However, in this dataset, we only focus on the cases in which the vehicle proceeds before the pedestrian. For example, the pedestrian is standing on the road or starting to cross but when he/she sees the car, he/she goes backward and let the driver proceed.

**Comment by Kalinga** [comment]
OKay, thanks! I suggest please keep this issue open for some more time for nomenclature related question, that would help future visitor to find at one place.

**Comment by Kalinga** [comment]
Hallo, I did not find any interface to extract video names depending on the camera used for recording.
In the paper it is mentioned that below cameras are used with different FOV
Garmin GDR-35 ,GoPro Hero+ ,Highscreen BB Connect
How to categories the videos with above camera types.

**Comment by ykotseruba** [comment]
There is no information on the camera type in the interface. Below is the list of videos that are taken with different cameras:
videos 1-60: GoPro Hero+ (1920x1980)
videos 61-70: Highscreen Box Connect (1280x720)
videos 71-346: Garmin GDR-35 (1920x1980)

**Comment by Kalinga** [comment]
Ok, thanks for the info!

**Comment by Kalinga** [comment]
Hallo, is there any information about vehicles current speed for a particular frame.

**Comment by ykotseruba** [comment]
Hi there,
we did not record vehicle information, only text tags for driver actions are available (e.g. slow down or speed up).

**Comment by Kalinga** [comment]
Thanks for your reply!
Is there a statistics, how many videos are with less than 5 second, or any such estimation related to video duration.

**Comment by ykotseruba** [comment]
The number of frames for each video can be found in the XML annotations under <size> tag.

**Comment by Kalinga** [comment]
Yes. Thank you!

**Comment by bsirmacek** [comment]
I cannot find the video clips on the given link. Are they removed?

**Comment by ykotseruba** [comment]
The videos were not removed but our server is down. Please check again later.
