### ISSUE TITLE
data format related problems

### ISSUE THREAD

**Issue by leoncesc** [ykotseruba/JAAD_dataset#8]
when I loaded video_0002, I met some problem in information of pedestrian1. The number of pose direction(158) in appearance is not the same as number of frames in ped_annotations(192), so how can we get the correspondence between the label of pose direction and ped_annotations, in other words, what is the corresponding frame index of pose direction ?

**Comment by ykotseruba** [comment]
Hi,
thanks for noticing the discrepancy, the annotations have been updated. Note that all appearance annotations have frame attribute, e.g. in the example below frame is 18 (tags are sorted in alphabetical order)
```
<box baby="0" backpack="0" bag_elbow="0" bag_hand="0" bag_left_side="0" bag_right_side="0" bag_shoulder="0" bicycle_motorcycle="0" cap="0" clothes_below_knee="0" clothes_lower_dark="1" clothes_lower_light="0" clothes_upper_dark="1" clothes_upper_light="0" frame="18" hood="0" object="0" phone="0" pose_back="0" pose_front="0" pose_left="1" pose_right="0" stroller_cart="0" sunglasses="0" umbrella="0" />
```
